version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ../../WebBE
      dockerfile: Dockerfile 
    restart: unless-stopped
    environment:
      - DEV_APP_PORT=3055
      - DEV_DB_HOST=mongo
      - DEV_DB_NAME=DaviWSV
      - JWT_SECRET=secret
    ports:
      - "3055:3055"